### ISSUE TITLE
Use web-ext

### ISSUE THREAD

**Issue by bfred-it** [HaNdTriX/webextension-toolbox#1]
I suggest leaving the manifest validation and packing to pre-existing tools offered by Mozilla (web-ext does both)

Also I'd rather see https://github.com/mozilla/webextension-polyfill added to manifest.json directly instead, e.g. [`ec960f0`](https://github.com/sindresorhus/refined-github/pull/798/commits/ec960f01443630369ddbd12d8a5f42a729e90cf6) — but perhaps it isn't a big deal, really, since it can't be automatically added to `options.html` this way.

**Comment by HaNdTriX** [comment]
@bfred-it thanks for your feedback!

> I suggest leaving the manifest validation and packing to pre-existing tools offered by Mozilla (web-ext does both)

Awesome I'll take a look if they work for other vendors (`chrome`, `opera`, `edge`) as well.

> Also I'd rather see https://github.com/mozilla/webextension-polyfill added to manifest.json directly instead, e.g. ec960f0 — but perhaps it isn't a big deal, really, since it can't be automatically added to options.html this way.

I choose to add the `webextension-polyfill` via [webpack provide plugin](https://webpack.js.org/plugins/provide-plugin/) in order to

* omit it on vendors that don't need it (`firefox`, `edge`)
* enable it in files that are not part of the `manifest.json` (e.g. [injected content scripts](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/executeScript))

Currently i use a forked version. As soon as they merge https://github.com/mozilla/webextension-polyfill/pull/82 I will add it as a dependency.

**Comment by HaNdTriX** [comment]
**Quick Update:** Webextension-Toolbox now uses `web-ext` when compiling the extension for firefox. 

https://github.com/HaNdTriX/webextension-toolbox/commit/b256052d9d658d503d0e43cbe2341df2a6e77315
